sudo: required
service: 
    - docker
before_install:
    - gem install bundler
    - gem update bundler
    - rvm use 1.8.7 --install --binary --fuzzy
    - docker build -t pavanpagan/docker-react -f Dockerfile.dev .

