sudo: required
language: node_js
node_js:
  - "8.15.1"
services:
  - docker

before_install:
  - docker build -t pavanpagan/docker-react -f Dockerfile.dev .

deploy: 
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-east-2-423694414493"
    bucket_path: "docker"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
        secure: "$AWS_SECRET_KEY"
