sudo: required
service: 
    - docker
before_install:
    - gem install bundler
    - gem install rake
    - gem install --path vendor/bundle
    - docker build -t pavanpagan/docker-react -f Dockerfile.dev .

