sudo: required
language: node_js
node_js:
  - "8.15.1"
services:
  - docker

before_install:
  - docker build -t pavanpagan/docker-react -f Dockerfile.dev .

script:
  - docker run pavanpagan/docker-react npm run test -- --coverage